## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring :
  datasource : 
    url : jdbc:mysql://localhost:3306/thigbilling?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username : root
    password :
#    jndi-name: jdbc/mysql
  jpa:
    properties:
      hibernate : 
         dialect : org.hibernate.dialect.MySQL5InnoDBDialect
         ddl-auto : auto
    show-sql: true
    
 
  